# --- OGÓLNE USTAWIENIA ---
set-option -g default-shell /bin/zsh
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
set-option -g renumber-windows on

# --- SKRÓTY KLAWISZOWE ---
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Odświeżanie konfiguracji
bind r source-file ~/.config/tmux/tmux.conf \; display-message "Config reloaded!"

# Splitowanie okien (intuicyjne)
bind | split-window -h -c "#{pane_current_path}"
bind _ split-window -v -c "#{pane_current_path}"
unbind '"'
unbind '%'

# Nawigacja po panelach (Twoje ustawienie h-t-n-s)
bind h select-pane -L
bind t select-pane -D 
bind n select-pane -U
bind s select-pane -R

# Switchowanie okien (Alt + Strzałki)
bind -n M-Left  previous-window
bind -n M-Right next-window

# --- PLUGINY (TPM) ---
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect' # Włączyłem ci oficjalny plugin do sesji

# --- KONFIGURACJA MOTYWU TOKYO NIGHT ---
set -g @plugin "janoamaral/tokyo-night-tmux"
set -g @tokyo-night-tmux_theme storm
set -g @tokyo-night-tmux_transparent 0
set -g @tokyo-night-tmux_window_id_style digital
set -g @tokyo-night-tmux_pane_id_style hsquare
set -g @tokyo-night-tmux_zoom_id_style dsquare
set -g @tokyo-night-tmux_show_path 1
set -g @tokyo-night-tmux_path_format relative
set -g @tokyo-night-tmux_terminal_icon 
set -g @tokyo-night-tmux_active_terminal_icon 
set -g @tokyo-night-tmux_show_wbg 1

# Inicjalizacja TPM (musi być na końcu)
run '~/.tmux/plugins/tpm/tpm'
